config/routes.rb
Rails.application.routes.draw do
  

 
  resources :charges
  resources :lessons

 

  mount StripeEvent::Engine => '/stripe-webhooks'

  devise_for :users, :controllers => { :registrations => 'users/registrations'}
  devise_scope :user do
    get 'subscribe', to: 'users/registrations#subscribe'
    put 'update_plan', to: 'users/registrations#update_plan'
    put 'update_card', to: 'users/registrations#update_card'
    put 'update_both', to: 'users/registrations#update_both'
    put 'cancel_plan', to: 'users/registrations#cancel_plan'
  end

  get 'pages/about'
  get 'pages/home'
 get 'pricing' => 'pages#pricing'

  get 'pages/contact'
  get 'thanks' => 'pages#thanks'
  get 'home' => 'pages#home'
  root 'lessons#index'

end

app/views/pages/about.html.erb
<h1>Welcome to Etsydemo!</h1>
<h2>Etsydemo is an online marketplace for buying and selling handmade goods.</h2>

app/views/pages/contact.html.erb
<h1>Email us at abc@etsydemo.com</h1>

app/views/pages/home.html.erb
<section class="top">
  <div class="max-width has-padding center">
    <h2>GET TO THE NEXT LEVEL</h2>
    <%= link_to "GET STARTED NOW", pricing_path, class: "btn btn-lg btn-default center", data: { no_turbolink: true } %>
  </div>
</section>




<section class="ideas">
  <div class="container">
    <header class="center">
      <h2>You'll get an edge on the field with instructional video lessons you can follow<br> from home and in the classroom
        with online tutoring.</h2>
      <h3>– DEAN GIBBONS, INSTRUCTOR &amp; CEO OF TELOS LAX </h3>

    </header>
  </div>
</section>

<section class="membership">
  <div class="container">
    <header class="center">

        <h1>Comprehensive Learning Platform</h1>
        <p>Build your foundation with the easiest and most intuitive learning platform. We provide all the resources and mentorship you need so you can focus on improving athletically and academically.</p>
    </header>
  </div>
</section>     
<div class="divider thin"></div>

    <section id="story" class="story section">
        <div class="container">
            <h2> What You Get</h2>
            <div class="row">
                <div class="overview col-md-6 col-sm-12 col-xs-12">
                    <h2 class="title">On The Field</h2>
                    <ul class="summary">
                      <li>High Quality Lessons From The Pros</li>
                      <li>Tailored Instruction To Your position</li>
                      <li>Tips and Explanations To Increase Lax IQ</li>
                      <li>Exercises to Increase Your Athleticism</li>
                    </ul>
 
                </div><!--//overview-->
                <div class="overview col-md-6 col-sm-12 col-xs-12">
                    <h2 class="title">In the Classroom</h2>
                    <ul class="summary">
                      <li>Direct Access to Online Tutor</li>
                      <li>Forum Support Focused Learning</li>
                      <li>Studying Tricks That Get You Smarter</li>
                      <li>Email Support 7 Days a week</li>
                    </ul>
                </div><!--//overview-->
            </div><!--//row-->
        </div><!--//container-->
    </section><!--//promo-->      



<div class="divider thin"></div>

<section class="membership">
  <div class="container">
    <header class="center">

        <h1>Who It's For</h1>
        <p>Youth Lacrosse Players Who Think School Is Just As Important</p>
    </header>
  </div>
</section>    


<div class="divider thin"></div>

<section class="action">
  <div class="max-width has-padding center">
    <h2>Get Your Edge <i>NOW</i></h2>
    <%= link_to "START LEARNING", pricing_path, class: "btn btn-lg btn-default center", data: { no_turbolink: true } %>
  </div>
</section>

app/views/pages/pricing.html.erb
<div class="container">
  <div class="masthead">
    <h1 class="signup-heading">Choose your enrollment option</h1>
    <h2 class="signup-subheading">You're gonna love it.</h2>
  </div>
    <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <h4 class="text-center">Step 1 of 2</h4>
      <div class="progress">
        <div class="progress-bar progress-bar-signup" role="progressbar" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100" style="width: 50%;">
        </div>
      </div>
    </div>
  </div>
</div>
    

<section class="pricing-tier">
  <div class="container has-padding">

    <div class="row">
      <div class="content col-md-12 col-sm-12 col-xs-12 text-center">
        <div class="thumbnail">
          
          <ul class="check">
                      <li>High Quality Lessons From The Pros</li>
                      <li>Tailored Instruction To Your position</li>
                      <li>Tips and Explanations To Increase Lax IQ</li>
                      <li>Exercises to Increase Your Athleticism</li>
                      <li>Direct Access to Online Tutor</li>
                      <li>Forum Support Focused Learning</li>
                      <li>Studying Tricks That Get You Smarter</li>
                      <li>Email Support 7 Days a week</li>
                      <li>Mentorship From Players &amp; Coaches</li>
          </ul>
          <div class="center">
            <%= link_to "Monthly Plan ", new_user_registration_path(plan: "monthly"), class: "btn btn-lg btn-default center" %>
            <h4>$20/month</h4>
            <h5>Billed Monthly</h5>
          </div>
          <div class="center">

            <%= link_to "Yearly Plan", new_user_registration_path(plan: "yearly"), class: "btn btn-lg btn-default center" %>
            <h4>$16/month </h4>
            <h5>Billed Yearly  20% OFF!</h5>    
          </div>
        </div>
      </div>
      </div>
  


  </div>
</section>

app/views/pages/thanks.html.erb
<div class="container">
	<div class="box">
    <h3 class="center">Welcome to BaseRails!</h3>
    <h4 class="center">We're excited to have you as a student. Please contact us if you have any comments, questions, or feedback. <br><br>Click below to get started!</h4>
		<div class="center">
			<%= link_to "Get started", lessons_path, class: "btn btn-primary" %>
		</div>
	</div>
</div>