config/routes.rb
Rails.application.routes.draw do
  

 
  resources :charges
  resources :lessons

 

  mount StripeEvent::Engine => '/stripe-webhooks'

  devise_for :users, :controllers => { :registrations => 'users/registrations'}
  devise_scope :user do
    get 'subscribe', to: 'users/registrations#subscribe'
    put 'update_plan', to: 'users/registrations#update_plan'
    put 'update_card', to: 'users/registrations#update_card'
    put 'update_both', to: 'users/registrations#update_both'
    put 'cancel_plan', to: 'users/registrations#cancel_plan'
  end

  get 'pages/about'
  get 'pages/home'
 get 'pricing' => 'pages#pricing'

  get 'pages/contact'
  get 'thanks' => 'pages#thanks'
  get 'home' => 'pages#home'
  root 'lessons#index'

end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :check_permission
  before_action :set_lesson, only: [:show, :edit, :update, :destroy]
  before_action :redirect_to_correct_url, only: [:show]
  before_action :require_admin, except: [:index, :show]
  

  # GET /videos
  # GET /videos.json
  def index
    if params[:category].blank?
      @lessons = Lesson.all.order("created_at DESC")
    else
      @category_id = Category.find_by(name: params[:category]).id
      @lessons = Lesson.where(category_id: @category_id).order("created_at DESC")  
    end
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
     @lesson = Lesson.find(params[:id])
  end

  # GET /videos/new
  def new
       @lesson = Lesson.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos
  # POST /videos.json
  def create
    @lesson = Lesson.new(lesson_params)

    respond_to do |format|
      if @lesson.save
        format.html { redirect_to @lesson, notice: 'Lesson was successfully created.' }
        format.json { render action: 'show', status: :created, location: @lesson }
      else
        format.html { render action: 'new' }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    respond_to do |format|
      if @lesson.update(lesson_params)
        format.html { redirect_to @lesson, notice: 'Video was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @lesson.destroy
    respond_to do |format|
      format.html { redirect_to lessons_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lesson
      @lesson = Lesson.find(params[:id])
    end

    def redirect_to_correct_url
      # Redirect to the correct URL if the title of the video has since been changed
      if request.path != lesson_path(@lesson)
        return redirect_to @lesson, :status => :moved_permanently
      end
    end

    def check_permission
      if user_signed_in?
        # User needs to have paid for extra_access or be subscribed
        if !current_user.extra_access && current_user.plan.blank?
          redirect_to subscribe_path, notice: "You need to be subscribed to access this content"
        end
      else
        # User needs to be signed in first
        redirect_to home_path, notice: "You must be logged in to access this section"
      end
    end


    # Never trust parameters from the scary internet, only allow the white list through.
  def lesson_params
      params.require(:lesson).permit(:title, :url)
    end
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/views/lessons/_form.html.erb
<%= form_for(@lesson) do |f| %>
  <% if @lesson.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lesson.errors.count, "error") %> prohibited this lesson from being saved:</h2>

      <ul>
      <% @lesson.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lessons/edit.html.erb
<h1>Editing lesson</h1>

<%= render 'form' %>

<%= link_to 'Show', @lesson %> |
<%= link_to 'Back', lessons_path %>

app/views/lessons/index.html.erb
<%= render 'pages/home' unless user_signed_in? %>
<h1>Listing lessons</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lessons.each do |lesson| %>
      <tr>
        <td><%= lesson.title %></td>
        <td><%= lesson.url %></td>
        <td><%= link_to 'Show', lesson %></td>
        <td><%= link_to 'Edit', edit_lesson_path(lesson) %></td>
        <td><%= link_to 'Destroy', lesson, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lesson', new_lesson_path %>

app/views/lessons/new.html.erb
<h1>New lesson</h1>

<%= render 'form' %>

<%= link_to 'Back', lessons_path %>

app/views/lessons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @lesson.title %>
</p>

<p>
  <strong>Url:</strong>
  <%= @lesson.url %>
</p>

<%= link_to 'Edit', edit_lesson_path(@lesson) %> |
<%= link_to 'Back', lessons_path %>