config/routes.rb
Rails.application.routes.draw do
  

 
  resources :charges
  resources :lessons

 

  mount StripeEvent::Engine => '/stripe-webhooks'

  devise_for :users, :controllers => { :registrations => 'users/registrations'}
  devise_scope :user do
    get 'subscribe', to: 'users/registrations#subscribe'
    put 'update_plan', to: 'users/registrations#update_plan'
    put 'update_card', to: 'users/registrations#update_card'
    put 'update_both', to: 'users/registrations#update_both'
    put 'cancel_plan', to: 'users/registrations#cancel_plan'
  end

  get 'pages/about'
  get 'pages/home'
 get 'pricing' => 'pages#pricing'

  get 'pages/contact'
  get 'thanks' => 'pages#thanks'
  get 'home' => 'pages#home'
  root 'lessons#index'

end

app/views/layouts/_footer.html.erb
<p>Copyright 2013</p>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-static-top navbar-default" role="navigation">
  <div class="container">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "Home", root_path, class: "navbar-brand" %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>


        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.name %> <b class="caret"></b></a>
          <ul class="dropdown-menu">
            
            <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
            <li><%= link_to "Manage Subscription", subscribe_path %></li>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
      <% else %>
        <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <li><%= link_to "Sign In", new_user_session_path %></li>
      <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Etsy</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "https://js.stripe.com/v2/" %>
  <%= csrf_meta_tags %>
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= tag :meta, :name => "stripe-key", :content => ENV["STRIPE_PUBLIC_KEY"] %>
</head>
<body>
  <%= render 'layouts/header' %>


  <%= yield %>



     <div id="push"></div>
    </div>

<%= render 'layouts/footer' %>


</body>
</html>